### ISSUE TITLE
Console.error logged when running component from inside react-test-renderer

### ISSUE THREAD

**Issue by scottdickerson** [joshwnj/react-visibility-sensor#131]
To reproduce, add the react-visibility-sensor to a component then test that component from inside react-test-render and you'll see this console error in the log.

React version 16.4.2
VisibilitySensor version: 4.1 
```
 Invariant Violation: Unable to find node on an unmounted component.
      
      at invariant (node_modules/fbjs/lib/invariant.js:42:15)
      at findCurrentFiberUsingSlowPath (node_modules/react-dom/cjs/react-dom.development.js:3779:30)
      at findCurrentHostFiber (node_modules/react-dom/cjs/react-dom.development.js:3887:23)
      at findHostInstance (node_modules/react-dom/cjs/react-dom.development.js:16825:19)
      at Object.findDOMNode (node_modules/react-dom/cjs/react-dom.development.js:17311:12)
      at Object.componentDidMount (node_modules/react-visibility-sensor/visibility-sensor.js:109:26)
      at Object.chainedFunction [as componentDidMount] (node_modules/create-react-class/factory.js:665:11)
      at commitLifeCycles (node_modules/react-cosmos-telescope/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:7019:22)
```

Here's a snippet of my component code:
``` <VisibilitySensor
      scrollCheck={true}
      partialVisibility={true}
      resizeCheck={true}
      key={`${name}tile`}>
      {({ isVisible }) => (
        <Tile>
```

See this underlying issue in React for more information:
https://github.com/facebook/react/issues/7371

**Comment by ddennis** [comment]
did you find a way to fix this?
